# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Christopher Mateo Pulupa Herrera
first_name: Christopher
middle_name: M.
last_name: Pulupa
email: christopher.pulupa@epn.edu.ec
description: > 
Estudiante de Ingeniería en Computación | EPN | Entusiasta de Redes y Cloud Computing. # the ">" symbol means to ignore newlines until "footer_text:"
footer_text: >
  © 2026 Christopher Pulupa.
keywords: jekyll, jekyll-theme, academic-website, portfolio-website, EPN, Computacion # add your own keywords or leave empty
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)
social:
  username: Mateosky1
  linkedin_username: christopher-pulupa  # Puedes cambiarlo por el tuyo exacto después
  github_username: Mateosky1
profile:
  align: right
  image: profpic.jpg
  address: >
    Quito, Ecuador<br />
    Escuela Politécnica Nacional

