title: Christopher Mateo Pulupa Herrera
first_name: Christopher
middle_name: Mateo
last_name: Pulupa Herrera
email: christopher.pulupa@epn.edu.ec
description: >
  Computer Science Student @ EPN | Network Enthusiast | Cloud Infrastructure Explorer
footer_text: >
  © 2026 Christopher Mateo Pulupa Herrera. Built with passion and code.

# CONFIGURACIÓN VISUAL
enforce_ssl: true
# Esto activa el modo oscuro por defecto (fondo negro)
enable_darkmode: true
display_type: dark 

# URLS
social:
  linkedin_username: christopher-pulupa
  github_username: Mateosky1
  email: christopher.pulupa@epn.edu.ec
url: https://Mateosky1.github.io
baseurl: ""
repository: Mateosky1/Mateosky1.github.io

# PLUGINS
plugins:
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji

# LIBRERÍAS INTERACTIVAS
third_party_libraries:
  mathjax: true
  bootstrap: true
  fontawesome: true
  academicons: true
  jquery: true

# REDES PROFESIONALES
social:
  linkedin_username: christopher-pulupa
  github_username: Mateosky1
  # twitch_username: TuUsuarioSiQuieres
